apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
  namespace: kafka
data:
  server.properties: |
    # Basic Kafka Configuration
    broker.id=${KAFKA_BROKER_ID}
    num.network.threads=3
    num.io.threads=8

    # Log Configuration
    log.dirs=/bitnami/kafka/data
    num.partitions=1
    default.replication.factor=3
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3

    # Listener Configuration
    listeners=PLAINTEXT://:9092
    advertised.listeners=PLAINTEXT://${MY_POD_NAME}.kafka-headless.kafka.svc.cluster.local:9092
    inter.broker.listener.name=PLAINTEXT
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT

    # Zookeeper Configuration
    zookeeper.connect=zookeeper:2181
    zookeeper.connection.timeout.ms=6000

    # Other Configuration
    delete.topic.enable=true
    auto.create.topics.enable=true
    transaction.state.log.min.isr=2

